Add 'exclude_installed_packages' setting
theforeman/foreman_rh_cloud pull request #350
Opened 2020-09-29 14:06 UTC by laviro

2020-09-30 15:50 UTC, ShimShtein requested changes

2020-09-30 15:50 UTC, ShimShtein commented on app/models/setting/rh_cloud.rb
> +      set('exclude_installed_packages', N_('Include all installed packages as part of the report for upload'), false),
```suggestion
      set('exclude_installed_packages', N_('Exclude installed packages from Red Hat cloud inventory report'), false),
```

2020-10-01 08:25 UTC, laviro commented on app/models/setting/rh_cloud.rb
> +      set('exclude_installed_packages', N_('Include all installed packages as part of the report for upload'), false),
Nice catch!

2020-10-01 14:08 UTC, ShimShtein approved these changes

2020-10-01 14:08 UTC, merged

2020-10-01 14:08 UTC, ShimShtein commented
Merged, thanks @laviro!