WIP - Add insights sorting to host index page
theforeman/foreman_rh_cloud pull request #361
Opened 2020-10-06 12:03 UTC by laviro

2020-10-07 13:27 UTC, laviro commented
Ready for review @ShimShtein

2020-10-11 14:37 UTC, ShimShtein requested changes
Two additional issues:

- [ ] Hosts that didn't have insights facet objects do not cache `inisghts_hits` correctly

- [ ] When we sort `desc`, `nil` values appear on top, instead of the bottom.

2020-10-11 14:50 UTC, ShimShtein commented
@adamruzicka, if I read correctly `scoped_search` [builder](https://github.com/wvanbergen/scoped_search/blob/master/lib/scoped_search/query_builder.rb#L587) of order by statements, there is no way we can influence `null first`/`null last` definition?

2020-10-14 07:46 UTC, adamruzicka commented
@ShimShtein I read it the same way :/

2020-10-14 15:33 UTC, ShimShtein requested changes
Small nitpick and we're done.

2020-10-14 15:33 UTC, ShimShtein commented on app/overrides/hosts_list.rb
> +  text: '<th class="hidden-xs" width="10%"><%= sort :"insights_recommendations_count", :as => _("Insights")%></th>'
```suggestion
  text: '<th class="hidden-xs" width="10%"><%= sort :insights_recommendations_count, :as => _("Insights")%></th>'
```

No need for string here.

2020-10-19 13:14 UTC, merged

2020-10-19 13:14 UTC, ShimShtein commented
Merged, thanks @laviro!