Add endpoints for proxying payload
theforeman/foreman_rh_cloud pull request #412
Opened 2020-11-16 10:35 UTC by xprazak2

Contains #375 and #325 in a single branch for easier testing. Needs https://github.com/redhataccess/foreman-plugin/pull/56

2020-11-16 16:40 UTC, ShimShtein requested changes
Unfortunately it breaks the older plugin. Found a couple of root causes.

2020-11-16 16:40 UTC, ShimShtein commented on app/controllers/insights_cloud/api/machine_telemetries_controller.rb
> +      @organization = @host.organization
This line fails for `redhat-access` plugin, when trying to configure the service and press "Check connection" button. The log is:

```
16:28:19 rails.1   | 2020-11-16T16:28:19 [I|app|215ee1cc] Started GET "/redhat_access/r/insights/view/api/v3/me" for 127.0.0.1 at 2020-11-16 16:28:19 +0000
16:28:19 rails.1   | 2020-11-16T16:28:19 [I|app|215ee1cc] Processing by InsightsCloud::Api::MachineTelemetriesController#forward_request as */*
16:28:19 rails.1   | 2020-11-16T16:28:19 [I|app|215ee1cc]   Parameters: {"path"=>"view/api/v3/me"}
16:28:19 rails.1   | 2020-11-16T16:28:19 [W|app|215ee1cc] Action failed
16:28:19 rails.1   | 2020-11-16T16:28:19 [I|app|215ee1cc] Backtrace for 'Action failed' error (NoMethodError): undefined method `organization' for nil:NilClass
16:28:19 rails.1   |  215ee1cc | /home/vagrant/foreman_rh_cloud/app/controllers/insights_cloud/api/machine_telemetries_controller.rb:58:in `ensure_org'
```

The same stack is produced by Insights -> Systems, if you have the username configured.

2020-11-18 09:28 UTC, xprazak2 commented
Let's keep the telemetry config for now since it is used in UI. I also added constraints to the routing which should fix the remaining problem.

2020-12-16 12:49 UTC, ShimShtein approved these changes

2021-02-07 08:06 UTC, ShimShtein commented
@xprazak2, I took the liberty to rebase your PR, since there were no significant changes.

2021-02-18 16:48 UTC, merged

2021-02-18 16:48 UTC, ShimShtein commented
Finally merged! Thanks @xprazak2!