Add Migration for new missing hosts table
theforeman/foreman_rh_cloud pull request #819
Opened 2023-05-15 15:17 UTC by chris1984

@ShimShtein here is the pr for the table

2023-05-16 13:06 UTC, ShimShtein requested changes
Can you please rename the file to have `.foreman_rh_cloud.rb` suffix? It should enable to roll forward or backward only plugin's migrations.
Upd: I suppose a model class should be in this PR too.

2023-05-17 08:36 UTC, ShimShtein commented
We are missing an `organization_id` field. The host should belong to the org that queried the cloud inventory.

2023-05-17 15:21 UTC, chris1984 commented
@ShimShtein updated.

2023-05-18 15:18 UTC, ShimShtein approved these changes

2023-05-18 15:18 UTC, merged