Add ability to generate report without uploading
theforeman/foreman_rh_cloud pull request #850
Opened 2023-10-23 18:57 UTC by chris1984

@ShimShtein here is the updated PR

2023-10-23 19:35 UTC, chris1984 commented on lib/foreman_inventory_upload/async/generate_report_job.rb
> +          ) if !disconnected
Rubocop was not happy with `unless disconnected` so changed it

2023-10-23 20:42 UTC, chris1984 commented
Are the tests failing because of my new param?

2023-10-24 18:35 UTC, ShimShtein requested changes

2023-10-24 18:35 UTC, ShimShtein commented on app/controllers/concerns/inventory_upload/report_actions.rb
>        ForemanTasks.async_task(ForemanInventoryUpload::Async::GenerateReportJob, ForemanInventoryUpload.generated_reports_folder, organization_id)
```suggestion
      ForemanTasks.async_task(ForemanInventoryUpload::Async::GenerateReportJob, ForemanInventoryUpload.generated_reports_folder, organization_id, disconnected)
```

2023-10-24 18:35 UTC, ShimShtein commented on lib/foreman_inventory_upload/async/generate_report_job.rb
> +          ) unless disconnected
This means that the action will not be executed at all if `disconnected` is set to `false`

2023-10-26 14:33 UTC, ShimShtein requested changes
You have missed a reference in https://github.com/theforeman/foreman_rh_cloud/blob/foreman_3_9/lib/foreman_inventory_upload/async/generate_all_reports_job.rb#L36 and https://github.com/theforeman/foreman_rh_cloud/blob/foreman_3_9/lib/tasks/rh_cloud_inventory.rake#L50
Besides that - looks good.

2023-10-26 17:05 UTC, chris1984 commented
> You have missed a reference in https://github.com/theforeman/foreman_rh_cloud/blob/foreman_3_9/lib/foreman_inventory_upload/async/generate_all_reports_job.rb#L36 and https://github.com/theforeman/foreman_rh_cloud/blob/foreman_3_9/lib/tasks/rh_cloud_inventory.rake#L50 Besides that - looks good.

Added the reference to disconnected on the genereate_all_reports_job.rb, the rake file already has the change you requested:

https://github.com/theforeman/foreman_rh_cloud/pull/850/files#diff-9ca8d337c7041b111f4dee13b8c59910e8ad72ca97ca82b0a3b845f68893555aR51

2023-10-26 17:07 UTC, chris1984 commented
@jameerpathan111 Can you test this change with CURL? Once this goes in I will make the hammer PR

2023-10-30 15:50 UTC, chris1984 commented
@jameerpathan111 

It looks like you can use hammer if you want instead of CURL, it picked up the new param with this pr checked out
```bash
[vagrant@hammer ~]$ hammer rh_report generate -h
Usage:
    hammer rh_report generate [OPTIONS]

Options:
 --disconnected BOOLEAN                  Generate the report, but do not upload
 --location[-id|-title] VALUE/NUMBER     Set the current location context for the request
 --organization[-id|-title] VALUE/NUMBER Set the current organization context for the request
 -h, --help                              Print help
```

2023-10-31 11:44 UTC, ShimShtein commented
We have missed a reference: https://github.com/theforeman/foreman_rh_cloud/blob/5745be80c865dad235c6c6057118ac8b1d26a8ab/lib/foreman_inventory_upload/async/generate_report_job.rb#L16C3-L17C31 should have the `disconnected` parameter passed too

2023-10-31 13:58 UTC, chris1984 commented
> We have missed a reference: https://github.com/theforeman/foreman_rh_cloud/blob/5745be80c865dad235c6c6057118ac8b1d26a8ab/lib/foreman_inventory_upload/async/generate_report_job.rb#L16C3-L17C31 should have the `disconnected` parameter passed too

@ShimShtein updated

2023-11-01 08:12 UTC, jameerpathan111 commented
@chris1984 @ShimShtein I was able to use api to generate a new report and also performed basic sanity checks on generated report. But I am not seeing `rh_report` subcommand in hammer, not sure why. I tried `foreman-rake apipie:cache` but it didn't help either.

2023-11-01 09:27 UTC, merged

2023-11-01 09:27 UTC, ShimShtein commented
Thanks @jameerpathan111 and @chris1984 !
Merged.

2023-11-01 14:14 UTC, chris1984 commented
> @chris1984 @ShimShtein I was able to use api to generate a new report and also performed basic sanity checks on generated report. But I am not seeing `rh_report` subcommand in hammer, not sure why. I tried `foreman-rake apipie:cache` but it didn't help either.

When this goes into a snap, we can test it with hammer and see if we see it. I spun up a centos7-hammer-devel box from forklift and it saw it right away, so maybe something was up with hammer on your box