rubocop --auto-correct
theforeman/foreman_rh_cloud pull request #868
Opened 2024-01-22 08:56 UTC by evgeni

2024-01-22 09:05 UTC, evgeni commented
no idea why the current CI didn't flag those rubocop offenses, but #866 did, so here we are.

2024-01-22 10:55 UTC, ekohl requested changes

2024-01-22 10:55 UTC, ekohl commented on config/routes.rb
> +      match '(/*path)(/)', :constraints => ->(req) { !req.path.include?('view/api') }, :to => 'machine_telemetries#forward_request', :via => [:get, :post, :delete, :put, :patch]
Wouldn't it be better to make it consistent this way:
```suggestion
      match '(/*path)(/)', constraints: ->(req) { !req.path.include?('view/api') },  to: 'machine_telemetries#forward_request', via: [:get, :post, :delete, :put, :patch]
```

2024-01-22 10:55 UTC, ekohl commented on lib/tasks/rh_cloud_inventory.rake
> +    if !ENV['organization_id'].nil?
Funny how the `generate_upload` is close, but not really the same in various subtle ways.

2024-01-22 11:04 UTC, evgeni commented on config/routes.rb
> +      match '(/*path)(/)', :constraints => ->(req) { !req.path.include?('view/api') }, :to => 'machine_telemetries#forward_request', :via => [:get, :post, :delete, :put, :patch]
consistent to what? the rest of the file uses both styles, so it's hard to say ;-)

(I don't mind either way, this is just what the :policeman: generated)

2024-01-22 13:39 UTC, ekohl commented on config/routes.rb
> +      match '(/*path)(/)', :constraints => ->(req) { !req.path.include?('view/api') }, :to => 'machine_telemetries#forward_request', :via => [:get, :post, :delete, :put, :patch]
I think my suggestion is a smaller diff and also more consistent within the file.

2024-01-22 14:42 UTC, ekohl approved these changes

2024-01-22 14:50 UTC, merged

2024-01-23 18:18 UTC, ShimShtein commented on lib/tasks/rh_cloud_inventory.rake
> +    if !ENV['organization_id'].nil?
We definitely can refactor both of them into using a helper method that will receive the action as lambda. Something along the lines of
``` ruby
with_organization_scope do |organization|
  ForemanTasks.async_task(InventorySync::Async::InventoryFullSync, organization)
end
```

Indeed it would be much prettier.