Pin remote execution to 12.0.5
theforeman/foreman_rh_cloud pull request #878
Opened 2024-03-28 17:31 UTC by chris1984

2024-04-03 10:00 UTC, ekohl commented on .github/workflows/ruby_tests.yml
> +      matrix_include: '[{"ruby": "2.7", "node": "16"}]'
Why include this? We don't run this combination anywhere.

2024-04-03 10:00 UTC, ekohl commented on gemfile.d/lock.rb
> +gem "foreman_remote_execution", "<= 12.0.5"
What's wrong with 12.0.6? Wouldn't semver suggest something like `< 13` would be more appropriate?

2024-04-03 13:14 UTC, chris1984 commented on .github/workflows/ruby_tests.yml
> +      matrix_include: '[{"ruby": "2.7", "node": "16"}]'
I'll remove this, this was me trying to figure out the JavaScript stuff until we found out it's in foreman.

2024-04-09 16:09 UTC, ekohl commented on package.json
> +  "version": "9.0.55",
This looks unrelated.

2024-04-09 16:09 UTC, ekohl commented on gemfile.d/lock.rb
> +gem "foreman_ansible", "< 14"
For CI you can also provide an environment variable like https://github.com/dm-drogeriemarkt/foreman_wreckingball/blob/861f54cab044dafddefffe9e0402b9aeb330ba80/.github/workflows/ci.yml#L34-L35

Then you can use `ENV['FOREMAN_VERSION']` in this file. That can be useful to be more future compatible: when you start to support newer versions then you don't want to forget about this.

I'm using https://github.com/dm-drogeriemarkt/foreman_wreckingball/pull/116 to verify this theory. If so, I'll properly document it.

2024-04-09 16:37 UTC, chris1984 commented
@ekohl is there anything extra I need to do to get the JS passing? I see the prs are merged in Foreman and Foreman-JS. Katello prs are passing now too.

2024-04-25 18:00 UTC, chris1984 commented
@ekohl Do you know how I can pin Katello 4.11 ?

2024-04-26 08:21 UTC, ekohl requested changes
Last thing is the Katello version.

2024-04-26 08:21 UTC, ekohl commented on gemfile.d/lock.rb
> +  gem "katello", "< 12"
I think you want
```suggestion
  gem "katello", "~> 4.11.0"
```

2024-04-26 08:21 UTC, ekohl commented on gemfile.d/lock.rb
> +  gem "foreman_remote_execution", "< 13"
Once https://github.com/Katello/katello/commit/4a91ec50461a5bbdac6929f7f4cb42eddb3a7afb is released this shouldn't be needed anymore, but for now this is ok.

2024-04-27 15:15 UTC, ekohl approved these changes

2024-04-29 12:19 UTC, merged