Add safe navigation if ip is nil on hosts sync
theforeman/foreman_rh_cloud pull request #885
Opened 2024-05-28 18:11 UTC by chris1984

### What are the changes introduced in this pull request?
* Adding a skip if `ip_addresses` is `nil`

### What are the testing steps for this pull request?
* Register a host, run inventory sync
* Unregister the host to run the missing hosts method
* Add in `ip_addresses = nil` at https://github.com/theforeman/foreman_rh_cloud/blob/v10/lib/inventory_sync/async/inventory_hosts_sync.rb#L70
* Run `foreman-rake rh_cloud_inventory:sync` and watch the `production.log` fail with `undefined method take_while for nil:NilClass (NoMethodError)`
* Apply PR and restart services
* Try the task and see that it completes without a traceback

2024-05-30 06:58 UTC, ShimShtein requested changes
I know it's a small issue, but can you please add a test case to https://github.com/theforeman/foreman_rh_cloud/blob/c74cfb41a6f3a398f04dc5bb049b17d5da0e95d9/test/jobs/inventory_hosts_sync_test.rb ?

Specifically we can add a mock record similar to the one we have on [line 58](https://github.com/theforeman/foreman_rh_cloud/blob/c74cfb41a6f3a398f04dc5bb049b17d5da0e95d9/test/jobs/inventory_hosts_sync_test.rb#L58), but without the `ip_addresses` field and modify a the [create records test](https://github.com/theforeman/foreman_rh_cloud/blob/c74cfb41a6f3a398f04dc5bb049b17d5da0e95d9/test/jobs/inventory_hosts_sync_test.rb#L298-L311) to make sure it creates a missing record for the new "missing" host too.

2024-06-05 17:23 UTC, chris1984 commented
@ShimShtein let me know what i'm missing with the test, it's still asserting 2 instead of 3. or we can talk about it tomorrow when we sync up.

2024-06-06 07:57 UTC, ShimShtein commented
@chris1984 you are not missing anything, actually you are adding too much here: https://github.com/theforeman/foreman_rh_cloud/pull/885/files#diff-1db2fc1b0779ffd29ad0788780a64b71490bad277d33887ef72e1283465b09d5R42

If you create a record in foreman, and create it in the Insights request mock, it means that it's not a missing host. This is why you have only two missing hosts, even though you have added a new one to the Insights request.
If you want to test for creation of a new missing host record, you need to make sure it exists only in Insights, and not in Foreman.

2024-06-06 13:52 UTC, chris1984 commented
@ShimShtein updated

2024-06-06 15:30 UTC, merged

2024-06-06 15:30 UTC, ShimShtein commented
Merged, thanks @chris1984 !