Update RuboCop configuration to inherit from theforeman-rubocop
theforeman/foreman_rh_cloud pull request #886
Opened 2024-05-31 09:01 UTC by archanaserver

- Added theforeman-rubocop as a development dependency in the gemspec.
- Changed the RuboCop configuration to inherit from default.yml provided
by theforeman-rubocop for better style alignment.
- Removed redundant cops as they are already included in the inherited
default.yml or not needed anymore.

default.yml: https://github.com/theforeman/theforeman-rubocop/?tab=readme-ov-file#basic-style---default-performance-and-rails-cops

This is part of Rubocop standerdization, link for the reference: https://community.theforeman.org/t/standardizing-rubocop-with-theforeman-rubocop/37239

2024-07-15 20:14 UTC, qcjames53 requested changes
Hi Archana!

I'm sorry it took me so long to review this PR, I wanted to triple check everything in the config file since this will end up being pretty important for devs and QE. I had a few questions and suggestions there but all in all everything looks great.

I expanded on this below but I don't *think* we can call `.update` on an `ActiveRecord::Relation`. It's not in any documentation I could find. I asked ChatGPT if the changes were ok and it said NO 3 times and YES once 🤷‍♂️. I'd put everything in a `.each` loop if validations are important and would keep the lines as `.update_all` if not.

2024-07-15 20:14 UTC, qcjames53 commented on .rubocop.yml
> +# inherit_from: .rubocop_todo.yml
This line can be safely removed.

2024-07-15 20:14 UTC, qcjames53 commented on .rubocop.yml
I noticed there are a few styles included in the [old rubocop config file](https://raw.githubusercontent.com/theforeman/foreman/2.3-stable/.rubocop.yml) that didn't make the jump over to this file (Style/CollectionMethods, Style/Documentation, Style/EmptyAssignment, etc). Is that intentional? The two new inclusions at the bottom (RaiseArgs and SkipsModelValidations) make sense to me.

I know this hardly matters but I think it would be great if this file were alphabetized for readability like the previous version. Would that be ok?

2024-07-15 20:14 UTC, qcjames53 commented on db/migrate/20210720000001_remove_old_insights_statuses.foreman_rh_cloud.rb
> +    InsightsClientReportStatus.where(status: 2).update(status: InsightsClientReportStatus::NO_REPORT)
This might be embarrassing if I'm incorrect here but I don't believe we can call `update` on an ActiveRecord::Relation as is done here. I asked ChatGPT for backup and it agreed with me :)

It seems like this will need to be a `.each do |record| record.update(...) end` kind of thing if we're looking to have validations run? Please let me know if I'm wrong here.

2024-07-15 20:14 UTC, qcjames53 commented on db/migrate/20221102110254_fix_rh_cloud_settings_category_to_dsl.rb
> +    Setting.where(category: 'Setting::RhCloud').update(category: 'Setting') if column_exists?(:settings, :category)
Same comment as above with the `update` thing.

2024-07-15 20:14 UTC, qcjames53 commented on lib/insights_cloud/async/insights_client_status_aging.rb
> +        InsightsClientReportStatus.where(host_id: host_ids).update(status: InsightsClientReportStatus::NO_REPORT)
Same as above.

2024-07-15 20:14 UTC, qcjames53 commented on lib/insights_cloud/async/insights_full_sync.rb
> +          InsightsFacet.for_organizations(organization.id).update(hits_count: 0)
Same as above.

2024-07-15 20:14 UTC, qcjames53 commented on test/unit/foreman_rh_cloud_self_host_test.rb
> +    Host.where(name: @host.name).update(name: @host.shortname)
Same as above.

2024-07-16 08:58 UTC, archanaserver commented
> I expanded on this below but I don't _think_ we can call `.update` on an `ActiveRecord::Relation`. 

Yes you are right, I had similar conversation few weeks back in one of my another PR on update and update_all, I misunderstood few things here in the code, but I was following the RuboCop doc: https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsskipsmodelvalidations So I did this to few other places as well that is disabling this cop because it is not safe to use.

2024-07-16 09:11 UTC, archanaserver commented on .rubocop.yml
> I noticed there are a few styles included in the [old rubocop config file](https://raw.githubusercontent.com/theforeman/foreman/2.3-stable/.rubocop.yml) that didn't make the jump over to this file (Style/CollectionMethods, Style/Documentation, Style/EmptyAssignment, etc). Is that intentional? The two new inclusions at the bottom (RaiseArgs and SkipsModelValidations) make sense to me.

What do you mean by this? Would you mind expanding a little more.


> I know this hardly matters but I think it would be great if this file were alphabetized for readability like the previous version. Would that be ok?

I don’t think we have specifically addressed alphabetizing RuboCop rules in our changes so far, but I can look into whether there is a cop for this and update it accordingly. Thanks for bringing this up; I believe it would be a good improvement for readability

2024-07-16 19:06 UTC, qcjames53 commented on .rubocop.yml
Hi Archana! For the old config file stuff, I looked through the file linked above and found these styles that used to be in the rubocop definition file but are now no longer included:
```
Style/Alias:
Style/AndOr:
Style/CollectionMethods:
Style/Documentation:
Style/EmptyMethod:
Style/FrozenStringLiteralComment:
Style/InverseMethods:
Style/MultipleComparison:
Style/ParallelAssignment:
Style/PreferredHashMethods:
Style/TernaryParentheses:
Style/TrailingCommaInArrayLiteral:
Style/TrailingCommaInHashLiteral:
```

We import a good amount of these styles through default.yml in theforeman-rubocop. Here is what's left:
```
Style/CollectionMethods:
Style/FrozenStringLiteralComment:
Style/InverseMethods:
Style/MultipleComparison:
Style/ParallelAssignment:
Style/PreferredHashMethods:
```

I didn't find these styles included anywhere I looked; is it OK to drop these requirements?

2024-07-16 19:09 UTC, qcjames53 reviewed
The changes look great to me, thank you! I'm totally ok with keeping `update_all` instead of refactoring into an each loop; I can see several ways that could end up a big headache. I just had one question about the included styles (posted elsewhere) but I'm happy to ACK once that is resolved.

2024-07-16 20:24 UTC, archanaserver reviewed
Dropping those cops from here because we already have it in theforeman-rubocop.

2024-07-16 20:24 UTC, archanaserver commented on .rubocop.yml
> For the old config file stuff, I looked through the file linked above and found these styles that used to 
> be in the rubocop definition file but are now no longer included:
> 
> ```
> Style/Alias:
> Style/AndOr:
> Style/CollectionMethods:
> Style/Documentation:
> Style/EmptyMethod:
> Style/FrozenStringLiteralComment:
> Style/InverseMethods:
> Style/MultipleComparison:
> Style/ParallelAssignment:
> Style/PreferredHashMethods:
> Style/TernaryParentheses:
> Style/TrailingCommaInArrayLiteral:
> Style/TrailingCommaInHashLiteral:
> ```
@qcjames53 so style cops which are not included in the config because we already have those in [theforeman-rubocop](https://github.com/theforeman/theforeman-rubocop), and we are inheriting this in rubocop config, so I believe we don't need to mention it again.

> Style/CollectionMethods:
> Style/FrozenStringLiteralComment:
> Style/InverseMethods:
> Style/MultipleComparison:
> Style/ParallelAssignment:
> Style/PreferredHashMethods:
> 
> I didn't find these styles included anywhere I looked; is it OK to drop these requirements?

Let's talk about each cops I have dropped here:

`Style/CollectionMethods`: I have dropped this one because I found that we don't need it, even after enabling I found no offenses, please correct me if I'm wrong or missing something. If adding this is good, I can add it here but looking at the old config, it was mentioned to disable it and that make no sense to add this in the config.
Same for `Style/InverseMethods`, `Style/MultipleComparison`, `Style/ParallelAssignment` and `Style/PreferredHashMethods`

`Style/FrozenStringLiteralComment`: We have this already, but enabled it to false, as mentioned in the old config.

2024-07-17 15:07 UTC, qcjames53 commented on .rubocop.yml
Thank you for the great explanation with this! That all sounds good to me. ACK'ing

2024-07-17 15:08 UTC, qcjames53 approved these changes

2024-07-17 15:53 UTC, chris1984 approved these changes
Thanks @archanaserver for your contribution and @qcjames53 for reviewing this, looks good from my end too.

2024-07-17 15:54 UTC, merged

2024-07-17 17:36 UTC, archanaserver commented
Thanks @chris1984 and @qcjames53 :)