Add Zeitwerk loader support
theforeman/foreman_rh_cloud pull request #892
Opened 2024-07-30 09:31 UTC by ofedoren

Not sure what's the right branch for opening PRs against :/

Not mergeable until deps are merged.

2024-09-03 13:26 UTC, ofedoren commented
Requires 4 plugins: tasks, rex, ansible, katello, I suggest revisiting this plugin after the deps are merged.

Not quire ready, probably some additional changes will be made.

2024-09-11 13:11 UTC, ekohl requested changes
We'll need to drop the temporary bits.

2024-09-11 13:11 UTC, ekohl commented on .github/workflows/ruby_tests.yml
> +      foreman_version: refs/pull/10131/head
The PR has been merged

2024-09-11 13:11 UTC, ekohl commented on gemfile.d/foreman_ansible.rb
> +gem 'foreman_ansible', github: 'ofedoren/foreman_ansible', branch: 'feat-37451-support-zeitwerk'
Has been merged & released

2024-09-11 13:11 UTC, ekohl commented on gemfile.d/foreman_remote_execution.local.rb
> +gem 'foreman_remote_execution', github: 'ofedoren/foreman_remote_execution', branch: 'feat-37453-support-zeitwerk'
Merged and released

2024-09-11 13:11 UTC, ekohl commented on gemfile.d/foreman_tasks.local.rb
> +gem 'foreman-tasks', github: 'ofedoren/foreman-tasks', branch: 'feat-37452-support-zeitwerk'
Merged and released

2024-09-11 13:11 UTC, ekohl commented on gemfile.d/katello.rb
> +gem 'katello', github: 'ofedoren/katello', branch: 'feat-37471-support-zeitwerk'
Still in review.

2024-09-11 14:09 UTC, ekohl commented on gemfile.d/katello.rb
> +gem 'katello', github: 'ofedoren/katello', branch: 'feat-37471-support-zeitwerk'
Also merged now

2024-09-11 15:01 UTC, ofedoren commented on gemfile.d/katello.rb
> +gem 'katello', github: 'ofedoren/katello', branch: 'feat-37471-support-zeitwerk'
I'm afraid we'd need to wait for Katello release?..

2024-09-11 15:04 UTC, ekohl commented on gemfile.d/katello.rb
> +gem 'katello', github: 'ofedoren/katello', branch: 'feat-37471-support-zeitwerk'
I think it's actually better to point to a git version of it, which wasn't there before. Right now it's not a concern, but if the matrix really was a matrix with multiple entries then it should also select the correct katello branch.

2024-09-11 15:07 UTC, ekohl approved these changes

2024-09-11 15:20 UTC, ekohl approved these changes

2024-09-11 15:26 UTC, ofedoren commented
Since it's green now, should I remove the last commit? Or leave it for you to decide when there is more appropriate timing?

2024-09-12 07:43 UTC, evgeni commented
I'd remove it, but I am also not the maintainer of this plugin :)

2024-09-12 18:55 UTC, jeremylenz commented
@ofedoren is this ready for merge?

2024-09-12 19:04 UTC, ekohl commented
This has a similar issue as what https://github.com/theforeman/foreman_virt_who_configure/pull/201 shows. Right now it's only testing with a released version of Katello, but that doesn't contain the Zeitwerk changes. Previously it added a `gemfile.d` file to use a git version, but now CI is red. If you add that change, katello-devel breaks.

2024-09-16 19:17 UTC, chris1984 commented
> This has a similar issue as what [theforeman/foreman_virt_who_configure#201](https://github.com/theforeman/foreman_virt_who_configure/pull/201) shows. Right now it's only testing with a released version of Katello, but that doesn't contain the Zeitwerk changes. Previously it added a `gemfile.d` file to use a git version, but now CI is red. If you add that change, katello-devel breaks.
> 
> Edit: I'm also entirely unsure how this repo does branching. The default is a `v10` branch and there is no concept of master/develop so does that mean it first needs to change the default branch to v11 since it's breaking? That's why I'm not merging this now.

@ekohl we used `v10` as the branch name since we needed a new release but we were in between Foreman releases for 6.16 

Talking with @ShimShtein he wanted to name the next branch v17 to more match the Satellite releases downstream so we know what version of satellite to attach things to for cherry-picks etc. 

We were going to make a new branch after Satellite 6.16 goes GA, but if it's blocking stuff, I can talk to Shim Thursday during our 1:1 and see if we can branch early.

2024-09-17 09:25 UTC, ShimShtein commented
@ekohl v10 is intended to be used with Foreman 6.12 (without Zeitwerk). I see this change will cause CI failures in the upstream, so let's switch to a new branch and make sure we're off the hook.

> Talking with @ShimShtein he wanted to name the next branch v17 to more match the Satellite releases downstream so we know what version of satellite to attach things to for cherry-picks etc.

I have also seen your comment about not attaching versions of plugins to downstream products (which is understandable). Any advice on better version numbering? Maybe attaching to the predicted Foreman version? Like calling the next one v13 (as it will go with Foreman 3.13)?

2024-09-17 13:12 UTC, jeremylenz commented
> Any advice on better version numbering? Maybe attaching to the predicted Foreman version? Like calling the next one v13 (as it will go with Foreman 3.13)?

Sure that sounds fine to me, but I think the more fundamental question is why does rh_cloud need to change its default branch every upstream major release? Why not just have a main or develop and then branch the same way as all other plugins?

2024-09-17 13:24 UTC, ShimShtein commented
> Why not just have a main or develop and then branch the same way as all other plugins?

Mainly historical reasons. Originally we were developing a couple of versions in parallel for the releases Satellite versions. Currently it's a bit less needed, although still, having the branch name to indicate what version of the plugin is currently under development sounds like a good idea to me. As I have said to Ewoud, it's a dilemma for me now, as both approaches have their own advantages.

Specifically in the case of Zeitwerk it's good that the PR wasn't merged, since the current branch is intended to be used with Foreman 3.12 which does not have Zeitwerk.

2024-09-19 17:31 UTC, ehelms commented
My 2 cents:

The `develop` branch should track with Foreman's develop branch. And if a branch is needed to track a released version of the plugin, create that branch. This is the model all the other plugins take, and we should pattern match for continuity, ease of understanding and procedure.

2024-09-20 13:38 UTC, ofedoren commented
Hmm, 1 of 3 test:foreman_rh_cloud tasks fails for some reason...

2024-09-20 14:16 UTC, ofedoren commented
... but now everything is green ...

2024-09-20 14:27 UTC, chris1984 commented
> ... but now everything is green ...

Merging

2024-09-20 14:32 UTC, chris1984 commented
Thanks @ofedoren

2024-09-20 14:32 UTC, merged